name: Telegram Notifications

on:
  pull_request:
    types: [opened, closed, reopened, synchronize]
  push:
    branches:
      - main  # Если у вас главная ветка называется "master", замените "main" на "master"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check Event Type and Send Telegram Notification
        run: |
          REPO_NAME="${{ github.repository }}"
          EVENT_TYPE="${{ github.event_name }}"

          if [[ "$EVENT_TYPE" == "pull_request" ]]; then
            PR_TITLE="${{ github.event.pull_request.title }}"
            PR_URL="${{ github.event.pull_request.html_url }}"
            PR_AUTHOR="${{ github.event.pull_request.user.login }}"
            PR_STATE="${{ github.event.action }}" # opened, closed, etc.

            MESSAGE="🛠 Pull Request в репозитории: ${REPO_NAME}
          🔹 Автор: ${PR_AUTHOR}
          🔹 Действие: ${PR_STATE}
          🔹 Название: ${PR_TITLE}
          🔗 [Открыть PR](${PR_URL})"

          elif [[ "$EVENT_TYPE" == "push" ]]; then
            COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
            COMMIT_AUTHOR="${{ github.event.head_commit.author.name }}"
            COMMIT_URL="${{ github.event.head_commit.url }}"

            MESSAGE="🚀 Обновлена главная ветка в репозитории: ${REPO_NAME}
          🔹 Автор: ${COMMIT_AUTHOR}
          🔹 Сообщение коммита: ${COMMIT_MESSAGE}
          🔗 [Посмотреть коммит](${COMMIT_URL})"
          fi

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=${MESSAGE}" 
